apiVersion: v1
kind: Service
metadata:
  name: bd-ml-service
spec:
  selector:
    app: bd-ml
  ports:
  - protocol: "TCP"
    port: 6532
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-ml
spec:
  selector:
    matchLabels:
      app: bd-ml
  replicas: 1
  template:
    metadata:
      name: bl-ml-app
      labels:
        app: bd-ml
    spec:
      volumes:
      - name: nfs-volume
        nfs: 
          server: 51.68.207.197
          path: /cluster/models
      containers:
      - name: bd-ml
        image: hub.osrsbotdetector.com/bot-detector/bd-ml:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "4500Mi"
            cpu: "2500m"
          requests:
            memory: "2500Mi"
            cpu: "2000m"
        ports:
        - containerPort: 6532
        volumeMounts:
        - name: nfs-volume
          mountPath: /MachineLearning/models
      imagePullSecrets:
      - name: regcred
