apiVersion: v1
kind: Service
metadata:
  name: bd-ml-service
spec:
  selector:
    app: bd-ml
  ports:
  - protocol: "TCP"
    port: 6532
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-ml
spec:
  selector:
    matchLabels:
      app: bd-ml
  replicas: 1
  template:
    metadata:
      name: bl-ml-app
      labels:
        app: bd-ml
    spec:
      containers:
      - name: bd-ml
        image: hub.osrsbotdetector.com/bot-detector/bd-ml:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6532
      imagePullSecrets:
      - name: regcred