version: '3'
services:
  machine-learning:
    build:
      context: ../bot-detector-ML
      dockerfile: Dockerfile
      args:
        root_path: /
        api_port: 8000
    image: bot-detector/bd-ml:latest
    env_file:
      - .env
    volumes:
      - ../bot-detector-ML/api/MachineLearning/models:/api/MachineLearning/models
    ports:
      - "8000:8000"