version: '3'
services:
  machine-learning:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        root_path: '/'
        api_port: 8000
    container_name: bd-ml
    command: uvicorn api.app:app --host 0.0.0.0 --reload --reload-include api/*
    env_file:
      - .env
    volumes:
      - ../bot-detector-ML/api:/project/api
    ports:
      - 8000:8000
    networks:
      - botdetector-network

networks:
  botdetector-network:
