apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bd-ml-hpa
spec:
  maxReplicas: 1 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bl-ml-app
  targetCPUUtilizationPercentage: 80 # target CPU utilization